/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-06-29

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "bootloader_dma.h"
#include "bootloader_usart.h"
#include "bootloader_gpio.h"

/* Private macro */
#define BOOTLOADER_DMABUFFERSIZE 100UL
#define BOOTLOADER_USART_BAUDRATE 115200UL
/* Private variables */
static uint32_t BootLoader_DMABuffer[BOOTLOADER_DMABUFFERSIZE];
enum BootLoader_CurrentState{
	BootLoader_ReceiveData,
	BootLoader_WaitForReception,
	BootLoader_TransmitData,
	BootLoader_WaitForTransmission,
	BootLoader_HandleError
}BootLoader_CurrentState = BootLoader_ReceiveData;
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	int32_t ReceivedDataCount;

	/* Initialize system clock to 180MHz */
	SystemCoreClockUpdate();
	/* Initialize the GPIO */
	BootLoader_GPIOInit();
	/* Initialize DMA */
	BootLoader_DMAInit(BootLoader_DMABuffer, BOOTLOADER_DMABUFFERSIZE);
	/* Initialize USART */
	BootLoader_USARTInit(BOOTLOADER_USART_BAUDRATE);
	/* Enable USART */
	BootLoader_USARTEnable();
	/* Enable interrupts */
	__enable_irq();

	while(1)
	{
		switch(BootLoader_CurrentState)
		{
			case BootLoader_ReceiveData:
				BootLoader_DMAReceiveEnable();
				BootLoader_CurrentState = BootLoader_WaitForReception;
				break;
			case BootLoader_WaitForReception:
				if(BootLoader_DataReceived)
				{
					BootLoader_DataReceived = 0;
					BootLoader_CurrentState = BootLoader_TransmitData;
				}
				else if(BootLoader_ReceiveError)
				{
					BootLoader_ReceiveError = 0;
					BootLoader_CurrentState = BootLoader_HandleError;
				}
				else
				{

				}
				break;
			case BootLoader_TransmitData:
				ReceivedDataCount = BootLoader_DMAGetReceivedDataCount();
				if(ReceivedDataCount > 0)
				{
					BootLoader_DMATransmitEnable((uint16_t)ReceivedDataCount);
					BootLoader_CurrentState = BootLoader_WaitForTransmission;
				}
				else
				{
					BootLoader_CurrentState = BootLoader_HandleError;
				}
				break;
			case BootLoader_WaitForTransmission:
				if(BootLoader_DataTransmitted)
				{
					BootLoader_CurrentState = BootLoader_ReceiveData;
					BootLoader_DataTransmitted = 0;
				}
				else if(BootLoader_TransmitError)
				{
					BootLoader_CurrentState = BootLoader_HandleError;
					BootLoader_TransmitError = 0;
				}
				else
				{

				}
				break;
			case BootLoader_HandleError:
			default:
				ASSERT(0);
				break;
		}
	}
}
